# This is a basic workflow to help you get started with Actions

name: Update database

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 * * * *'
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: tellormonitors

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deployment
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - run: python3 -m venv venv && source venv/bin/activate
      - run: pip install -r requirements.txt
      - name: update DB
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          HEROKU_POSTGRESQL_ONYX_URL: ${{ secrets.HEROKU_POSTGRESQL_ONYX_URL }}
        run: cd scripts && python monitor.py
